# Generated by Django 5.1.3 on 2025-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_verified_customuser_email_verified_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_cooldown',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
