# Generated by Django 5.1.3 on 2025-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_reset_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
