# Generated by Django 5.1.3 on 2025-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.CharField(blank=True, default='email', max_length=255, null=True),
        ),
    ]
