# Generated by Django 5.1.3 on 2025-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
