# Generated by Django 5.1.3 on 2025-02-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
