name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -t ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /var/www
        if [ ! -d "mindshaft" ]; then
            git clone git@github.com:huzaifa003/mindshaft.git
        else
            cd mindshaft
            git reset --hard HEAD
            git pull origin main
        fi

        cd /var/www/mindshaft
        if [ ! -d "venv" ]; then
            python3 -m venv venv
        fi
        source venv/bin/activate
        pip install -r requirements.txt

        cd /var/www/mindshaft/mindshaft
        python manage.py migrate
        python manage.py collectstatic --noinput

        sudo systemctl restart mindshaft-gunicorn
        sudo systemctl reload nginx
        EOF
